<?php

namespace Database\Seeders;

use App\Models\Assunto;
use App\Models\Autor;
use App\Models\Livro;
use Illuminate\Database\Seeder;

class LivroSeeder extends Seeder
{
    public function run(): void
    {
        $livros = [
            [
                'titulo' => 'Dom Casmurro',
                'editora' => 'Editora Ática',
                'edicao' => 2,
                'ano_publicacao' => '1899',
                'valor' => 45.90,
                'autores' => ['Machado de Assis'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Clássico', 'Realismo'],
            ],
            [
                'titulo' => 'Memórias Póstumas de Brás Cubas',
                'editora' => 'Nova Fronteira',
                'edicao' => 1,
                'ano_publicacao' => '1881',
                'valor' => 39.90,
                'autores' => ['Machado de Assis'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Clássico', 'Realismo'],
            ],
            [
                'titulo' => 'Quincas Borba',
                'editora' => 'Editora Ática',
                'edicao' => 1,
                'ano_publicacao' => '1891',
                'valor' => 38.00,
                'autores' => ['Machado de Assis'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Realismo'],
            ],
            [
                'titulo' => 'A Hora da Estrela',
                'editora' => 'Rocco',
                'edicao' => 1,
                'ano_publicacao' => '1977',
                'valor' => 39.90,
                'autores' => ['Clarice Lispector'],
                'assuntos' => ['Literatura Brasileira', 'Romance'],
            ],
            [
                'titulo' => 'A Paixão Segundo G.H.',
                'editora' => 'Rocco',
                'edicao' => 2,
                'ano_publicacao' => '1964',
                'valor' => 42.00,
                'autores' => ['Clarice Lispector'],
                'assuntos' => ['Literatura Brasileira', 'Ficção'],
            ],
            [
                'titulo' => 'O Alquimista',
                'editora' => 'HarperCollins',
                'edicao' => 1,
                'ano_publicacao' => '1988',
                'valor' => 42.00,
                'autores' => ['Paulo Coelho'],
                'assuntos' => ['Ficção', 'Autoajuda'],
            ],
            [
                'titulo' => 'Brida',
                'editora' => 'HarperCollins',
                'edicao' => 1,
                'ano_publicacao' => '1990',
                'valor' => 37.90,
                'autores' => ['Paulo Coelho'],
                'assuntos' => ['Ficção', 'Fantasia'],
            ],
            [
                'titulo' => 'Gabriela Cravo e Canela',
                'editora' => 'Companhia das Letras',
                'edicao' => 3,
                'ano_publicacao' => '1958',
                'valor' => 55.00,
                'autores' => ['Jorge Amado'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Regionalismo'],
            ],
            [
                'titulo' => 'Capitães da Areia',
                'editora' => 'Companhia das Letras',
                'edicao' => 2,
                'ano_publicacao' => '1937',
                'valor' => 48.00,
                'autores' => ['Jorge Amado'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Drama'],
            ],
            [
                'titulo' => 'Tereza Batista Cansada de Guerra',
                'editora' => 'Companhia das Letras',
                'edicao' => 1,
                'ano_publicacao' => '1972',
                'valor' => 52.00,
                'autores' => ['Jorge Amado'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Regionalismo'],
            ],
            [
                'titulo' => 'Grande Sertão Veredas',
                'editora' => 'Nova Fronteira',
                'edicao' => 1,
                'ano_publicacao' => '1956',
                'valor' => 62.50,
                'autores' => ['Guimarães Rosa'],
                'assuntos' => ['Literatura Brasileira', 'Ficção', 'Clássico', 'Regionalismo'],
            ],
            [
                'titulo' => 'Sagarana',
                'editora' => 'Nova Fronteira',
                'edicao' => 1,
                'ano_publicacao' => '1946',
                'valor' => 44.00,
                'autores' => ['Guimarães Rosa'],
                'assuntos' => ['Literatura Brasileira', 'Conto', 'Regionalismo'],
            ],
            [
                'titulo' => 'Alguma Poesia',
                'editora' => 'Companhia das Letras',
                'edicao' => 1,
                'ano_publicacao' => '1930',
                'valor' => 35.00,
                'autores' => ['Carlos Drummond de Andrade'],
                'assuntos' => ['Poesia', 'Modernismo', 'Literatura Brasileira'],
            ],
            [
                'titulo' => 'Sentimento do Mundo',
                'editora' => 'Companhia das Letras',
                'edicao' => 1,
                'ano_publicacao' => '1940',
                'valor' => 33.00,
                'autores' => ['Carlos Drummond de Andrade'],
                'assuntos' => ['Poesia', 'Literatura Brasileira'],
            ],
            [
                'titulo' => 'O Romance d\'A Pedra do Reino',
                'editora' => 'José Olympio',
                'edicao' => 1,
                'ano_publicacao' => '1971',
                'valor' => 68.00,
                'autores' => ['Ariano Suassuna'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Regionalismo', 'Cordel'],
            ],
            [
                'titulo' => 'O Auto da Compadecida',
                'editora' => 'Agir',
                'edicao' => 4,
                'ano_publicacao' => '1955',
                'valor' => 41.00,
                'autores' => ['Ariano Suassuna'],
                'assuntos' => ['Teatro', 'Literatura Brasileira', 'Cordel'],
            ],
            [
                'titulo' => 'Vidas Secas',
                'editora' => 'Record',
                'edicao' => 2,
                'ano_publicacao' => '1938',
                'valor' => 36.90,
                'autores' => ['Graciliano Ramos'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Realismo', 'Regionalismo'],
            ],
            [
                'titulo' => 'São Bernardo',
                'editora' => 'Record',
                'edicao' => 1,
                'ano_publicacao' => '1934',
                'valor' => 34.00,
                'autores' => ['Graciliano Ramos'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Realismo'],
            ],
            [
                'titulo' => 'Macunaíma',
                'editora' => 'Texto Editores',
                'edicao' => 3,
                'ano_publicacao' => '1928',
                'valor' => 38.00,
                'autores' => ['Mário de Andrade'],
                'assuntos' => ['Literatura Brasileira', 'Ficção', 'Modernismo'],
            ],
            [
                'titulo' => 'O Tempo e o Vento',
                'editora' => 'Companhia das Letras',
                'edicao' => 1,
                'ano_publicacao' => '1949',
                'valor' => 75.00,
                'autores' => ['Érico Veríssimo'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'História do Brasil'],
            ],
            [
                'titulo' => 'O Quinze',
                'editora' => 'José Olympio',
                'edicao' => 2,
                'ano_publicacao' => '1930',
                'valor' => 32.00,
                'autores' => ['Rachel de Queiroz'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Regionalismo'],
            ],
            [
                'titulo' => 'As Meninas',
                'editora' => 'Companhia das Letras',
                'edicao' => 1,
                'ano_publicacao' => '1973',
                'valor' => 43.00,
                'autores' => ['Lygia Fagundes Telles'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Drama'],
            ],
            [
                'titulo' => 'O Cortiço',
                'editora' => 'Ática',
                'edicao' => 5,
                'ano_publicacao' => '1890',
                'valor' => 29.90,
                'autores' => ['Aluísio Azevedo'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Naturalismo', 'Clássico'],
            ],
            [
                'titulo' => 'Iracema',
                'editora' => 'Ática',
                'edicao' => 3,
                'ano_publicacao' => '1865',
                'valor' => 27.50,
                'autores' => ['José de Alencar'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Romantismo', 'Clássico'],
            ],
            [
                'titulo' => 'Os Sertões',
                'editora' => 'Nova Aguilar',
                'edicao' => 1,
                'ano_publicacao' => '1902',
                'valor' => 58.00,
                'autores' => ['Euclides da Cunha'],
                'assuntos' => ['Literatura Brasileira', 'História do Brasil', 'Clássico', 'Realismo'],
            ],
            [
                'titulo' => 'O Triste Fim de Policarpo Quaresma',
                'editora' => 'Penguin',
                'edicao' => 1,
                'ano_publicacao' => '1915',
                'valor' => 33.00,
                'autores' => ['Lima Barreto'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Clássico'],
            ],
            [
                'titulo' => 'Reinações de Narizinho',
                'editora' => 'Brasiliense',
                'edicao' => 6,
                'ano_publicacao' => '1931',
                'valor' => 31.00,
                'autores' => ['Monteiro Lobato'],
                'assuntos' => ['Literatura Infantojuvenil', 'Ficção', 'Fantasia'],
            ],
            [
                'titulo' => 'Lavoura Arcaica',
                'editora' => 'Companhia das Letras',
                'edicao' => 1,
                'ano_publicacao' => '1975',
                'valor' => 46.00,
                'autores' => ['Raduan Nassar'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Drama'],
            ],
            [
                'titulo' => 'Relato de um Certo Oriente',
                'editora' => 'Companhia das Letras',
                'edicao' => 1,
                'ano_publicacao' => '1989',
                'valor' => 44.00,
                'autores' => ['Milton Hatoum'],
                'assuntos' => ['Literatura Brasileira', 'Romance'],
            ],
            [
                'titulo' => 'Feliz Ano Novo',
                'editora' => 'Companhia das Letras',
                'edicao' => 2,
                'ano_publicacao' => '1975',
                'valor' => 41.00,
                'autores' => ['Rubem Fonseca'],
                'assuntos' => ['Literatura Brasileira', 'Conto', 'Suspense'],
            ],
            [
                'titulo' => 'A República dos Bugres',
                'editora' => 'Record',
                'edicao' => 1,
                'ano_publicacao' => '1999',
                'valor' => 48.00,
                'autores' => ['Rubem Fonseca'],
                'assuntos' => ['Literatura Brasileira', 'Romance', 'Thriller'],
            ],
            [
                'titulo' => 'Poema Sujo',
                'editora' => 'Civilização Brasileira',
                'edicao' => 1,
                'ano_publicacao' => '1976',
                'valor' => 29.00,
                'autores' => ['Ferreira Gullar'],
                'assuntos' => ['Poesia', 'Literatura Brasileira', 'Memórias'],
            ],
        ];

        foreach ($livros as $dados) {
            $livro = Livro::firstOrCreate(
                ['titulo' => $dados['titulo']],
                [
                    'editora' => $dados['editora'],
                    'edicao' => $dados['edicao'],
                    'ano_publicacao' => $dados['ano_publicacao'],
                    'valor' => $dados['valor'],
                ],
            );

            $autoresIds = Autor::whereIn('nome', $dados['autores'])->pluck('cod_au');
            $assuntosIds = Assunto::whereIn('descricao', $dados['assuntos'])->pluck('cod_as');

            $livro->autores()->sync($autoresIds);
            $livro->assuntos()->sync($assuntosIds);
        }
    }
}
